title: Awesome Historic(al) Maps
description: A curated list of historic(al) map resources, tools, databases, search engines, and collections.
url: https://stark1tty.github.io
baseurl: /awesome-historical-maps

plugins:
  - jekyll-seo-tag

exclude:
  - ci/
  - .setup/
  - development/
  - backup_.gitignore~
  - code-of-conduct.md
  - contributing.md
  - license
